env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  camelcase: off
  no-console: off
  import/extensions: off
  no-await-in-loop: off
  no-underscore-dangle: [1, { allow: ['__dirname'] }]
  max-len: ["error", {
    "code": 120,
    "ignoreComments": true,
    "ignoreTrailingComments": true,
    "ignoreUrls": true,
    "ignoreStrings": true,
    "ignoreTemplateLiterals": true
  }]
